# Generated by Django 4.2.7 on 2023-11-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiagnosisResult',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('crop_category', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('STRAWBERRY', 'Strawberry'), ('TOMATO', 'Tomato'), ('PEPPER', 'Pepper'), ('CUCUMBER', 'Cucumber')], max_length=50)),
                ('crop_status', models.CharField(blank=True, choices=[('알 수 없음', 'Unknown'), ('정상', 'Healthy'), ('오류', 'Error'), ('잿빛곰팡이병', 'Gray Mold'), ('흰가루병', 'Powdery Mildew'), ('노균병', 'Downy Mildew'), ('탄저병', 'Anthracnose'), ('다량원소결핍(N)', 'Macronutrient Deficiency Nitrogen'), ('다량원소결핍(P)', 'Macronutrient Deficiency Phosphorus'), ('다량원소결핍(K)', 'Macronutrient Deficiency Potassium'), ('열과', 'Dehiscence'), ('냉해피해', 'Cold Injury'), ('칼슘결핍', 'Calcium Deficiency ')], max_length=50)),
                ('probability_ranking', models.JSONField()),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.userdiagnosisrequest')),
                ('request_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.requestuser')),
            ],
            options={
                'db_table': 'user_diagnosis_report',
                'managed': True,
            },
        ),
    ]
