# Generated by Django 4.2.7 on 2023-11-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiagnosisResult',
            fields=[
                ('id', models.UUIDField(default='fb4f1925c0bd4df39e63716e28287189', editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('crop_category', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('STRAWBERRY', 'Strawberry'), ('TOMATO', 'Tomato'), ('PEPPER', 'Pepper'), ('CUCUMBER', 'Cucumber')], max_length=50)),
                ('crop_status', models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy'), ('ERROR', 'Error'), ('TOMATO_GRAY_MOLD', 'Tomato Gray Mold'), ('TOMATO_POWDERY_MILDEW', 'Tomato Powdery Mildew'), ('TOMATO_MACRONUTRIENT_DEFICIENCY', 'Tomato Macronutrient Deficiency'), ('TOMATO_DEHISCENCE', 'Tomato Dehiscence'), ('STRAWBERRY_GRAY_MOLD', 'Strawberry Gray Mold'), ('STRAWBERRY_POWDERY_MILDEW', 'Strawberry Powdery Mildew'), ('STRAWBERRY_MACRONUTRIENT_DEFICIENCY', 'Strawberry Macronutrient Deficiency'), ('STRAWBERRY_COLD_INJURY', 'Strawberry Cold Injury'), ('CUCUMBER_DOWNY_MILDEW', 'Cucumber Downy Mildew'), ('CUCUMBER_POWDERY_MILDEW', 'Cucumber Powdery Mildew'), ('CUCUMBER_MACRONUTRIENT_DEFICIENCY', 'Cucumber Macronutrient Deficiency'), ('CUCUMBER_COLD_INJURY', 'Cucumber Cold Injury'), ('PEPPER_ANTHRACNOSE', 'Pepper Anthracnose'), ('PEPPER_POWDERY_MILDEW', 'Pepper Powdery Mildew'), ('PEPPER_MACRONUTRIENT_DEFICIENCY', 'Pepper Macronutrient Deficiency')], max_length=50)),
                ('probability_ranking', models.JSONField()),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnosis.userdiagnosisrequest')),
                ('request_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.requestuser')),
            ],
            options={
                'db_table': 'user_diagnosis_report',
                'managed': True,
            },
        ),
    ]
