# Generated by Django 4.2.7 on 2023-11-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiagnosisresult',
            name='id',
            field=models.UUIDField(default='1dcb69271ba148daaee6cd8397d1e928', editable=False, primary_key=True, serialize=False),
        ),
    ]
