# Generated by Django 4.2.7 on 2023-11-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_userdiagnosisresult_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiagnosisresult',
            name='id',
            field=models.UUIDField(default='17891e935a304ffd860a35bd6ed78062', editable=False, primary_key=True, serialize=False),
        ),
    ]
