# Generated by Django 4.2.7 on 2023-11-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiagnosisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='requests/blobs/')),
                ('crop_category', models.CharField(default='UNKNOWN', max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('requested_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
