# Generated by Django 4.2.7 on 2023-11-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiagnosisRequest',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='static/uploads/blob/%Y/%m/%d/')),
                ('crop_category', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('STRAWBERRY', 'Strawberry'), ('TOMATO', 'Tomato'), ('PEPPER', 'Pepper'), ('CUCUMBER', 'Cucumber')], default='UNKNOWN', max_length=50)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_user_uuid', to='accounts.requestuser')),
                ('retry_request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_request_uuid', to='diagnosis.userdiagnosisrequest')),
            ],
        ),
    ]
