# Generated by Django 4.2.7 on 2023-11-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiagnosisrequest',
            name='crop_category',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('STRAWBERRY', 'Strawberry'), ('TOMATO', 'Tomato'), ('PEPPER', 'Pepper'), ('CUCUMBER', 'Cucumber')], default='UNKNOWN', max_length=50),
        ),
    ]
